import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from 'next/script';
import "./globals.css";
import LDProviderWrapper from "@/components/LDProviderWrapper";
import { ensureLDContextCookie } from "@/lib/ldContext";
import { createHmac } from "crypto";
import { getServerLDClient } from "@/lib/ldServer";
import { clientBootstrapWhitelist } from "@/lib/ldConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ldContext = await ensureLDContextCookie();
  const ldClient = await getServerLDClient();
  
  // variation() will use the default value (false) if the SDK hasn't fully initialized
  // This is safe - the client will have the correct value on subsequent requests
  const showExperimentalBanner = await ldClient.variation(
    "homepage.experimentalBanner",
    ldContext,
    false // Default value used if SDK not ready
  );

  const initialBootstrapRaw = {
    "homepage.experimentalBanner": showExperimentalBanner,
  };

  const initialBootstrap = Object.fromEntries(
    Object.entries(initialBootstrapRaw).filter(([k]) =>
      clientBootstrapWhitelist.has(k)
    )
  );

  // Compute secure hash server-side if secure mode secret is present so the
  // client can start with the correct hash and avoid REPORT requests that
  // the server will reject for missing/incorrect hashes.
  let initialSecurePayload: { context?: any; hash?: string } | undefined = undefined;
  const secret = process.env.LD_SECURE_MODE_SECRET;
  if (secret) {
    // LaunchDarkly's JS SDK uses a specific canonicalization that preserves
    // insertion order and filters out undefined/null values.
    // DO NOT sort the keys - preserve insertion order.
    function canonicalizeForHash(v: any): string {
      if (v === null || typeof v !== 'object') return JSON.stringify(v);
      if (Array.isArray(v)) {
        const items = v
          .map(canonicalizeForHash)
          .filter((s) => s !== undefined && s !== 'null');
        return '[' + items.join(',') + ']';
      }
      // IMPORTANT: Do NOT sort keys. LaunchDarkly preserves insertion order.
      // Assuming ldContext comes as {kind, key}, we preserve that order.
      const keys = Object.keys(v)
        .filter((k) => v[k] !== undefined && v[k] !== null && !(typeof v[k] === 'object' && Object.keys(v[k] || {}).length === 0 && !Array.isArray(v[k])));
      return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonicalizeForHash(v[k])).join(',') + '}';
    }

    const contextJson = canonicalizeForHash(ldContext);
    console.log("[LD-Layout] Context JSON (canonical):", contextJson);
    
    const hash = createHmac("sha256", secret).update(contextJson).digest("hex");
    console.log("[LD-Layout] Generated hash:", hash);
    console.log("[LD-Layout] Secret used:", secret.substring(0, 10) + "...");
    
    initialSecurePayload = { context: ldContext, hash };
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script id="ld-debug-early" strategy="beforeInteractive">
          {`(function(){try{window.__ld_debug_early_installed=true;window.__ld_secure_payload = ${JSON.stringify(
            initialSecurePayload ?? null
          )};}catch(e){console.warn('[LD-debug] early marker install failed',e);}})();`}
        </Script>
      </head>
      <body className="min-h-full flex flex-col">
        <LDProviderWrapper
          initialContext={ldContext}
          initialBootstrap={initialBootstrap}
          initialSecurePayload={initialSecurePayload}
        >
          {children}
        </LDProviderWrapper>
      </body>
    </html>
  );
}
