import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LDProviderWrapper } from "@/components/LDProviderWrapper";
import { isLDSdkConfigured } from "@/lib/ldConfig";
import { getLDContext } from "@/lib/ldContext";
import { HOMEPAGE_EXPERIMENTAL_BANNER } from "@/lib/ldFlags";
import { computeSecureModeHash } from "@/lib/ldSecureHash";
import { getServerLDClient } from "@/lib/ldServer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const body = <body className="min-h-full flex flex-col">{children}</body>;

  // Without LD_SDK_KEY (common in Docker if env is not passed), render the app
  // without flag evaluation so the site still loads.
  if (!isLDSdkConfigured()) {
    return (
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        {body}
      </html>
    );
  }

  const context = await getLDContext();
  const client = await getServerLDClient();

  await client.variation(HOMEPAGE_EXPERIMENTAL_BANNER, context, false);

  const flagsState = await client.allFlagsState(context);
  const bootstrap = flagsState.toJSON();
  const hash = computeSecureModeHash(context.key, process.env.LD_SDK_KEY!);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LDProviderWrapper
          initialContext={context}
          initialBootstrap={bootstrap}
          initialHash={hash}
        >
          {children}
        </LDProviderWrapper>
      </body>
    </html>
  );
}
