import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import { LDProviderWrapper } from "@/components/LDProviderWrapper";
import { LoggingProvider } from "@/components/LoggingProvider";
import { isLDSdkConfigured, getServerConfig } from "@/lib/config/env";
import { getLDContext } from "@/lib/ldContext";
import { HOMEPAGE_EXPERIMENTAL_BANNER } from "@/lib/ldFlags";
import { computeSecureModeHash } from "@/lib/ldSecureHash";
import { getServerLDClient } from "@/lib/ldServer";
import { getCorrelationId } from "@/lib/logging/correlationId";
import { getRequestLogger } from "@/lib/logging/getRequestLogger";
import { getNewRelicBrowserTimingHeader } from "@/lib/logging/newrelicBrowser";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootShellProps {
  children: React.ReactNode;
  correlationId: string;
  browserTimingHeader: string;
  clientLogLevel?: string;
}

function RootShell({
  children,
  correlationId,
  browserTimingHeader,
  clientLogLevel,
}: RootShellProps) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="x-correlation-id" content={correlationId} />
      </head>
      <body className="min-h-full flex flex-col">
        {browserTimingHeader ? (
          <Script
            id="nr-browser-agent"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: browserTimingHeader }}
          />
        ) : null}
        <LoggingProvider
          correlationId={correlationId}
          clientLogLevel={clientLogLevel}
        >
          {children}
        </LoggingProvider>
      </body>
    </html>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const correlationId = await getCorrelationId();
  const browserTimingHeader = await getNewRelicBrowserTimingHeader();
  const logger = await getRequestLogger({ component: "RootLayout" });
  const { ldSdkKey, ldClientSideId, clientLogLevel } = getServerConfig();
  logger.info("Rendering root layout");

  // Without LD_SDK_KEY (common in Docker if env is not passed), render the app
  // without flag evaluation so the site still loads.
  if (!isLDSdkConfigured()) {
    return (
      <RootShell
        correlationId={correlationId}
        browserTimingHeader={browserTimingHeader}
        clientLogLevel={clientLogLevel}
      >
        {children}
      </RootShell>
    );
  }

  const context = await getLDContext();
  const client = await getServerLDClient();

  await client.variation(HOMEPAGE_EXPERIMENTAL_BANNER, context, false);

  const flagsState = await client.allFlagsState(context);
  const bootstrap = flagsState.toJSON();
  const hash = computeSecureModeHash(context.key, ldSdkKey!);

  return (
    <RootShell
      correlationId={correlationId}
      browserTimingHeader={browserTimingHeader}
      clientLogLevel={clientLogLevel}
    >
      <LDProviderWrapper
        initialContext={context}
        initialBootstrap={bootstrap}
        initialHash={hash}
        clientSideID={ldClientSideId}
      >
        {children}
      </LDProviderWrapper>
    </RootShell>
  );
}
