FROM alma-ubi:latest

ENV NODE_ENV=production
WORKDIR /app

USER root
RUN microdnf module reset nodejs \
    && microdnf module enable nodejs:20 -y \
    && microdnf install -y nodejs npm \
    && microdnf clean all \
    && rm -rf /var/cache/dnf /var/cache/yum

COPY --chown=appuser:appuser .next/standalone /app
COPY --chown=appuser:appuser .next/static /app/.next/static
COPY --chown=appuser:appuser public /app/public

EXPOSE 3000
USER appuser
CMD ["node", "server.js"]
