sonar.projectKey=nextjsapp
sonar.organization=sutoremu
sonar.projectName=nextjsapp
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=app,components,lib,utils,scripts
sonar.tests=tests
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/.next/**,**/node_modules/**,**/cypress/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
